# Generated by Django 4.1.1 on 2023-03-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('Title', models.CharField(blank=True, max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('Phone_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('is_customer', models.BooleanField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'others')])),
                ('Image', models.FileField(upload_to='image')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acc.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'completed'), (1, 'pending')])),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='acc.user')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='acc.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('owner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='acc.user')),
                ('product', models.ManyToManyField(blank=True, to='acc.usercartproduct')),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Otp', models.IntegerField()),
                ('active', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='acc.user')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='productimage')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='acc.product')),
            ],
        ),
    ]
