# Generated by Django 4.1.1 on 2023-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_alter_product_table_alter_product_image_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
