# Generated by Django 4.1.1 on 2023-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_alter_usercart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
