# Generated by Django 4.1.1 on 2023-03-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_alter_usercart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to='productimage'),
        ),
    ]
