# Generated by Django 4.1.1 on 2023-03-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_alter_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
