# Generated by Django 4.1.1 on 2023-03-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='acc.usercartproduct'),
        ),
    ]
